//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ScorekeeperDBModel", "FK__Hole__CourseId__0AD2A005", "Course", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scorekeeper.Course), "Hole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scorekeeper.Hole), true)]
[assembly: EdmRelationshipAttribute("ScorekeeperDBModel", "FK__Rounds__CourseId__1273C1CD", "Course", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Scorekeeper.Course), "Rounds", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scorekeeper.Round), true)]
[assembly: EdmRelationshipAttribute("ScorekeeperDBModel", "FK__RoundScor__HoleI__173876EA", "Hole", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Scorekeeper.Hole), "RoundScore", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scorekeeper.RoundScore), true)]
[assembly: EdmRelationshipAttribute("ScorekeeperDBModel", "FK__Rounds__UserId__117F9D94", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Scorekeeper.User), "Rounds", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scorekeeper.Round), true)]
[assembly: EdmRelationshipAttribute("ScorekeeperDBModel", "FK__RoundScor__Round__164452B1", "Rounds", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Scorekeeper.Round), "RoundScore", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scorekeeper.RoundScore), true)]
[assembly: EdmRelationshipAttribute("ScorekeeperDBModel", "FK_RoundFinalScore_Course", "Course", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Scorekeeper.Course), "RoundFinalScore", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scorekeeper.RoundFinalScore), true)]
[assembly: EdmRelationshipAttribute("ScorekeeperDBModel", "FK_RoundFinalScore_Users", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Scorekeeper.User), "RoundFinalScore", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scorekeeper.RoundFinalScore), true)]

#endregion

namespace Scorekeeper
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ScorekeeperDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ScorekeeperDBEntities object using the connection string found in the 'ScorekeeperDBEntities' section of the application configuration file.
        /// </summary>
        public ScorekeeperDBEntities() : base("name=ScorekeeperDBEntities", "ScorekeeperDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ScorekeeperDBEntities object.
        /// </summary>
        public ScorekeeperDBEntities(string connectionString) : base(connectionString, "ScorekeeperDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ScorekeeperDBEntities object.
        /// </summary>
        public ScorekeeperDBEntities(EntityConnection connection) : base(connection, "ScorekeeperDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Course> Courses
        {
            get
            {
                if ((_Courses == null))
                {
                    _Courses = base.CreateObjectSet<Course>("Courses");
                }
                return _Courses;
            }
        }
        private ObjectSet<Course> _Courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hole> Hole
        {
            get
            {
                if ((_Hole == null))
                {
                    _Hole = base.CreateObjectSet<Hole>("Hole");
                }
                return _Hole;
            }
        }
        private ObjectSet<Hole> _Hole;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Round> Rounds
        {
            get
            {
                if ((_Rounds == null))
                {
                    _Rounds = base.CreateObjectSet<Round>("Rounds");
                }
                return _Rounds;
            }
        }
        private ObjectSet<Round> _Rounds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RoundScore> RoundScore
        {
            get
            {
                if ((_RoundScore == null))
                {
                    _RoundScore = base.CreateObjectSet<RoundScore>("RoundScore");
                }
                return _RoundScore;
            }
        }
        private ObjectSet<RoundScore> _RoundScore;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RoundFinalScore> RoundFinalScore
        {
            get
            {
                if ((_RoundFinalScore == null))
                {
                    _RoundFinalScore = base.CreateObjectSet<RoundFinalScore>("RoundFinalScore");
                }
                return _RoundFinalScore;
            }
        }
        private ObjectSet<RoundFinalScore> _RoundFinalScore;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourses(Course course)
        {
            base.AddObject("Courses", course);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hole EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHole(Hole hole)
        {
            base.AddObject("Hole", hole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rounds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRounds(Round round)
        {
            base.AddObject("Rounds", round);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoundScore EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoundScore(RoundScore roundScore)
        {
            base.AddObject("RoundScore", roundScore);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoundFinalScore EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoundFinalScore(RoundFinalScore roundFinalScore)
        {
            base.AddObject("RoundFinalScore", roundFinalScore);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScorekeeperDBModel", Name="Course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Course : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Course object.
        /// </summary>
        /// <param name="courseId">Initial value of the CourseId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Course CreateCourse(global::System.Guid courseId, global::System.String name)
        {
            Course course = new Course();
            course.CourseId = courseId;
            course.Name = name;
            return course;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                if (_CourseId != value)
                {
                    OnCourseIdChanging(value);
                    ReportPropertyChanging("CourseId");
                    _CourseId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CourseId");
                    OnCourseIdChanged();
                }
            }
        }
        private global::System.Guid _CourseId;
        partial void OnCourseIdChanging(global::System.Guid value);
        partial void OnCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK__Hole__CourseId__0AD2A005", "Hole")]
        public EntityCollection<Hole> Hole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Hole>("ScorekeeperDBModel.FK__Hole__CourseId__0AD2A005", "Hole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Hole>("ScorekeeperDBModel.FK__Hole__CourseId__0AD2A005", "Hole", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK__Rounds__CourseId__1273C1CD", "Rounds")]
        public EntityCollection<Round> Rounds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Round>("ScorekeeperDBModel.FK__Rounds__CourseId__1273C1CD", "Rounds");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Round>("ScorekeeperDBModel.FK__Rounds__CourseId__1273C1CD", "Rounds", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK_RoundFinalScore_Course", "RoundFinalScore")]
        public EntityCollection<RoundFinalScore> RoundFinalScore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RoundFinalScore>("ScorekeeperDBModel.FK_RoundFinalScore_Course", "RoundFinalScore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RoundFinalScore>("ScorekeeperDBModel.FK_RoundFinalScore_Course", "RoundFinalScore", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScorekeeperDBModel", Name="Hole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hole object.
        /// </summary>
        /// <param name="holeId">Initial value of the HoleId property.</param>
        public static Hole CreateHole(global::System.Guid holeId)
        {
            Hole hole = new Hole();
            hole.HoleId = holeId;
            return hole;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid HoleId
        {
            get
            {
                return _HoleId;
            }
            set
            {
                if (_HoleId != value)
                {
                    OnHoleIdChanging(value);
                    ReportPropertyChanging("HoleId");
                    _HoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HoleId");
                    OnHoleIdChanged();
                }
            }
        }
        private global::System.Guid _HoleId;
        partial void OnHoleIdChanging(global::System.Guid value);
        partial void OnHoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                OnCourseIdChanging(value);
                ReportPropertyChanging("CourseId");
                _CourseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CourseId");
                OnCourseIdChanged();
            }
        }
        private Nullable<global::System.Guid> _CourseId;
        partial void OnCourseIdChanging(Nullable<global::System.Guid> value);
        partial void OnCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HoleNumber
        {
            get
            {
                return _HoleNumber;
            }
            set
            {
                OnHoleNumberChanging(value);
                ReportPropertyChanging("HoleNumber");
                _HoleNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HoleNumber");
                OnHoleNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _HoleNumber;
        partial void OnHoleNumberChanging(Nullable<global::System.Int32> value);
        partial void OnHoleNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Distance
        {
            get
            {
                return _Distance;
            }
            set
            {
                OnDistanceChanging(value);
                ReportPropertyChanging("Distance");
                _Distance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Distance");
                OnDistanceChanged();
            }
        }
        private Nullable<global::System.Int32> _Distance;
        partial void OnDistanceChanging(Nullable<global::System.Int32> value);
        partial void OnDistanceChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK__Hole__CourseId__0AD2A005", "Course")]
        public Course Course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("ScorekeeperDBModel.FK__Hole__CourseId__0AD2A005", "Course").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("ScorekeeperDBModel.FK__Hole__CourseId__0AD2A005", "Course").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Course> CourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("ScorekeeperDBModel.FK__Hole__CourseId__0AD2A005", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Course>("ScorekeeperDBModel.FK__Hole__CourseId__0AD2A005", "Course", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK__RoundScor__HoleI__173876EA", "RoundScore")]
        public EntityCollection<RoundScore> RoundScore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RoundScore>("ScorekeeperDBModel.FK__RoundScor__HoleI__173876EA", "RoundScore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RoundScore>("ScorekeeperDBModel.FK__RoundScor__HoleI__173876EA", "RoundScore", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScorekeeperDBModel", Name="Round")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Round : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Round object.
        /// </summary>
        /// <param name="roundId">Initial value of the RoundId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="courseId">Initial value of the CourseId property.</param>
        public static Round CreateRound(global::System.Guid roundId, global::System.Guid userId, global::System.Guid courseId)
        {
            Round round = new Round();
            round.RoundId = roundId;
            round.UserId = userId;
            round.CourseId = courseId;
            return round;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RoundId
        {
            get
            {
                return _RoundId;
            }
            set
            {
                if (_RoundId != value)
                {
                    OnRoundIdChanging(value);
                    ReportPropertyChanging("RoundId");
                    _RoundId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoundId");
                    OnRoundIdChanged();
                }
            }
        }
        private global::System.Guid _RoundId;
        partial void OnRoundIdChanging(global::System.Guid value);
        partial void OnRoundIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                OnCourseIdChanging(value);
                ReportPropertyChanging("CourseId");
                _CourseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CourseId");
                OnCourseIdChanged();
            }
        }
        private global::System.Guid _CourseId;
        partial void OnCourseIdChanging(global::System.Guid value);
        partial void OnCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoundNumber
        {
            get
            {
                return _RoundNumber;
            }
            set
            {
                OnRoundNumberChanging(value);
                ReportPropertyChanging("RoundNumber");
                _RoundNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoundNumber");
                OnRoundNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _RoundNumber;
        partial void OnRoundNumberChanging(Nullable<global::System.Int32> value);
        partial void OnRoundNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PlayedDate
        {
            get
            {
                return _PlayedDate;
            }
            set
            {
                OnPlayedDateChanging(value);
                ReportPropertyChanging("PlayedDate");
                _PlayedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayedDate");
                OnPlayedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PlayedDate;
        partial void OnPlayedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPlayedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK__Rounds__CourseId__1273C1CD", "Course")]
        public Course Course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("ScorekeeperDBModel.FK__Rounds__CourseId__1273C1CD", "Course").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("ScorekeeperDBModel.FK__Rounds__CourseId__1273C1CD", "Course").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Course> CourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("ScorekeeperDBModel.FK__Rounds__CourseId__1273C1CD", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Course>("ScorekeeperDBModel.FK__Rounds__CourseId__1273C1CD", "Course", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK__Rounds__UserId__117F9D94", "User")]
        public User Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ScorekeeperDBModel.FK__Rounds__UserId__117F9D94", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ScorekeeperDBModel.FK__Rounds__UserId__117F9D94", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ScorekeeperDBModel.FK__Rounds__UserId__117F9D94", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("ScorekeeperDBModel.FK__Rounds__UserId__117F9D94", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK__RoundScor__Round__164452B1", "RoundScore")]
        public EntityCollection<RoundScore> RoundScore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RoundScore>("ScorekeeperDBModel.FK__RoundScor__Round__164452B1", "RoundScore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RoundScore>("ScorekeeperDBModel.FK__RoundScor__Round__164452B1", "RoundScore", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScorekeeperDBModel", Name="RoundFinalScore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RoundFinalScore : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RoundFinalScore object.
        /// </summary>
        /// <param name="roundFinalScoreId">Initial value of the RoundFinalScoreId property.</param>
        /// <param name="courseId">Initial value of the CourseId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="playedDate">Initial value of the PlayedDate property.</param>
        public static RoundFinalScore CreateRoundFinalScore(global::System.Guid roundFinalScoreId, global::System.Guid courseId, global::System.Guid userId, global::System.DateTime playedDate)
        {
            RoundFinalScore roundFinalScore = new RoundFinalScore();
            roundFinalScore.RoundFinalScoreId = roundFinalScoreId;
            roundFinalScore.CourseId = courseId;
            roundFinalScore.UserId = userId;
            roundFinalScore.PlayedDate = playedDate;
            return roundFinalScore;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RoundFinalScoreId
        {
            get
            {
                return _RoundFinalScoreId;
            }
            set
            {
                if (_RoundFinalScoreId != value)
                {
                    OnRoundFinalScoreIdChanging(value);
                    ReportPropertyChanging("RoundFinalScoreId");
                    _RoundFinalScoreId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoundFinalScoreId");
                    OnRoundFinalScoreIdChanged();
                }
            }
        }
        private global::System.Guid _RoundFinalScoreId;
        partial void OnRoundFinalScoreIdChanging(global::System.Guid value);
        partial void OnRoundFinalScoreIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                OnCourseIdChanging(value);
                ReportPropertyChanging("CourseId");
                _CourseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CourseId");
                OnCourseIdChanged();
            }
        }
        private global::System.Guid _CourseId;
        partial void OnCourseIdChanging(global::System.Guid value);
        partial void OnCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FinalScore
        {
            get
            {
                return _FinalScore;
            }
            set
            {
                OnFinalScoreChanging(value);
                ReportPropertyChanging("FinalScore");
                _FinalScore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinalScore");
                OnFinalScoreChanged();
            }
        }
        private Nullable<global::System.Int32> _FinalScore;
        partial void OnFinalScoreChanging(Nullable<global::System.Int32> value);
        partial void OnFinalScoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PlayedDate
        {
            get
            {
                return _PlayedDate;
            }
            set
            {
                OnPlayedDateChanging(value);
                ReportPropertyChanging("PlayedDate");
                _PlayedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayedDate");
                OnPlayedDateChanged();
            }
        }
        private global::System.DateTime _PlayedDate;
        partial void OnPlayedDateChanging(global::System.DateTime value);
        partial void OnPlayedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK_RoundFinalScore_Course", "Course")]
        public Course Course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("ScorekeeperDBModel.FK_RoundFinalScore_Course", "Course").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("ScorekeeperDBModel.FK_RoundFinalScore_Course", "Course").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Course> CourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("ScorekeeperDBModel.FK_RoundFinalScore_Course", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Course>("ScorekeeperDBModel.FK_RoundFinalScore_Course", "Course", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK_RoundFinalScore_Users", "User")]
        public User Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ScorekeeperDBModel.FK_RoundFinalScore_Users", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ScorekeeperDBModel.FK_RoundFinalScore_Users", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ScorekeeperDBModel.FK_RoundFinalScore_Users", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("ScorekeeperDBModel.FK_RoundFinalScore_Users", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScorekeeperDBModel", Name="RoundScore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RoundScore : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RoundScore object.
        /// </summary>
        /// <param name="roundScoreId">Initial value of the RoundScoreId property.</param>
        /// <param name="roundId">Initial value of the RoundId property.</param>
        /// <param name="holeId">Initial value of the HoleId property.</param>
        public static RoundScore CreateRoundScore(global::System.Guid roundScoreId, global::System.Guid roundId, global::System.Guid holeId)
        {
            RoundScore roundScore = new RoundScore();
            roundScore.RoundScoreId = roundScoreId;
            roundScore.RoundId = roundId;
            roundScore.HoleId = holeId;
            return roundScore;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RoundScoreId
        {
            get
            {
                return _RoundScoreId;
            }
            set
            {
                if (_RoundScoreId != value)
                {
                    OnRoundScoreIdChanging(value);
                    ReportPropertyChanging("RoundScoreId");
                    _RoundScoreId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoundScoreId");
                    OnRoundScoreIdChanged();
                }
            }
        }
        private global::System.Guid _RoundScoreId;
        partial void OnRoundScoreIdChanging(global::System.Guid value);
        partial void OnRoundScoreIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RoundId
        {
            get
            {
                return _RoundId;
            }
            set
            {
                OnRoundIdChanging(value);
                ReportPropertyChanging("RoundId");
                _RoundId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoundId");
                OnRoundIdChanged();
            }
        }
        private global::System.Guid _RoundId;
        partial void OnRoundIdChanging(global::System.Guid value);
        partial void OnRoundIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid HoleId
        {
            get
            {
                return _HoleId;
            }
            set
            {
                OnHoleIdChanging(value);
                ReportPropertyChanging("HoleId");
                _HoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HoleId");
                OnHoleIdChanged();
            }
        }
        private global::System.Guid _HoleId;
        partial void OnHoleIdChanging(global::System.Guid value);
        partial void OnHoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Strokes
        {
            get
            {
                return _Strokes;
            }
            set
            {
                OnStrokesChanging(value);
                ReportPropertyChanging("Strokes");
                _Strokes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Strokes");
                OnStrokesChanged();
            }
        }
        private Nullable<global::System.Int32> _Strokes;
        partial void OnStrokesChanging(Nullable<global::System.Int32> value);
        partial void OnStrokesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK__RoundScor__HoleI__173876EA", "Hole")]
        public Hole Hole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hole>("ScorekeeperDBModel.FK__RoundScor__HoleI__173876EA", "Hole").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hole>("ScorekeeperDBModel.FK__RoundScor__HoleI__173876EA", "Hole").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Hole> HoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hole>("ScorekeeperDBModel.FK__RoundScor__HoleI__173876EA", "Hole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Hole>("ScorekeeperDBModel.FK__RoundScor__HoleI__173876EA", "Hole", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK__RoundScor__Round__164452B1", "Rounds")]
        public Round Rounds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("ScorekeeperDBModel.FK__RoundScor__Round__164452B1", "Rounds").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("ScorekeeperDBModel.FK__RoundScor__Round__164452B1", "Rounds").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Round> RoundsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("ScorekeeperDBModel.FK__RoundScor__Round__164452B1", "Rounds");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Round>("ScorekeeperDBModel.FK__RoundScor__Round__164452B1", "Rounds", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScorekeeperDBModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        public static User CreateUser(global::System.Guid userId, global::System.String username)
        {
            User user = new User();
            user.UserId = userId;
            user.Username = username;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK__Rounds__UserId__117F9D94", "Rounds")]
        public EntityCollection<Round> Rounds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Round>("ScorekeeperDBModel.FK__Rounds__UserId__117F9D94", "Rounds");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Round>("ScorekeeperDBModel.FK__Rounds__UserId__117F9D94", "Rounds", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScorekeeperDBModel", "FK_RoundFinalScore_Users", "RoundFinalScore")]
        public EntityCollection<RoundFinalScore> RoundFinalScore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RoundFinalScore>("ScorekeeperDBModel.FK_RoundFinalScore_Users", "RoundFinalScore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RoundFinalScore>("ScorekeeperDBModel.FK_RoundFinalScore_Users", "RoundFinalScore", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
